### ISSUE TITLE
Your instruction is probably incomplete

### ISSUE THREAD

**Issue by Doroshenko-T** [kth8/llama-server#1]
Hi,
I want to try your llama-server on Linux Alma 9.
Unfortunately, this instruction of yours does not work:

```
docker run \
    -d \
    --name llama1b \
    --init \
    -p 8080:8080/tcp \
    ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
```
I run it, but I get the error of missing a command, and execution stops.
Apparently, the reason for this error is caused by an incomplete instruction.

Could you present it in a complete and understandable way, step by step?

**Comment by kth8** [comment]
@T-Shilov I assume that is because you don't have Docker installed. Alma Linux should have `podman` installed by default which can be used as a replacement in this case so replace `docker` with `podman`.
```
podman run \
    -d \
    --name llama1b \
    --init \
    -p 8080:8080/tcp \
    ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
```

**Comment by Doroshenko-T** [comment]
Ok, I did that, and got this result:
```
$ podman run \
    -d \
    --name llama1b \
    --init \
    -p 8080:8080/tcp \
    ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
Trying to pull ghcr.io/kth8/llama-server:llama-3.2-1b-instruct...
Getting image source signatures
Copying blob 0aacda3dfb23 done   | 
Copying blob d31415fe5fdc done   | 
Copying config 1c0a872abc done   | 
Writing manifest to image destination
042a0ec153bb19ac5684e4b195a4bcbaa4e7ce757eb3f5ecafa6c88b11046277
```

Now how do we use it all?
Once again, I ask you to prepare a complete instruction on the use of your project, from A to Z, so that I do not ask you additional questions.

**Comment by kth8** [comment]
Since this is a server, you will need a client that is "OpenAI API compatible". There are many options available. Open WebUI is a popular option. Msty and Jan.ai are also compatible desktop apps I've used in the past. The fastest way to get an answer is to use the `curl` command from the README.

I'm afraid I can't provide every possible way to use the OpenAI API. I'm also curious how you found this project since I haven't told a single other person about it nor did I actually expect anyone but myself to use it.

**Comment by Doroshenko-T** [comment]
I am often interested in publications in the thread https://github.com/ollama/ollama/issues/2453 , and I was familiarizing myself with your posts there :-)

But I have no way of getting the RX580 to work yet. It seems to be a dead end for me, so I went back to using the CPU. Sure, it's very slow, but it works always and everywhere.
That's why I got interested in Georgi Gerganov's project, which promises faster speed with CPU.
Yes, I used to use Open WebUI client, but it horrified me with its huge size and the fact that it distorts the answers of console llama, so I will try to use a simpler and faster Page Assist instead.

What do I need to specify in the browser address bar of a remote client computer to connect to your server?
And how do I change the code of your server to use llama 3.1?

**Comment by kth8** [comment]
Page assist added OpenAI support in the latest release so that as well as just going to `http://localhost:8080/` in your browser are probably the most space efficient ways to use the API other than from the CLI. If you are accessing from another computer then use the IP address of the server this is running on. Models larger than 3B such as Llama3.1 8B I found too slow to use with CPU only on consumer hardware so I didn't include it. llamafile has 3.1 8B https://huggingface.co/Mozilla/Meta-Llama-3.1-8B-Instruct-llamafile

**Comment by Doroshenko-T** [comment]
Unfortunately, the link http://localhost:8080 / does not open your server.
The check confirms this:

```
$ nmap localhist  -p1-8192
Starting Nmap 7.92 ( https://nmap.org ) at 2024-10-19 18:00 EEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00017s latency).
Not shown: 8191 closed tcp ports (conn-refused)
PORT   STATE SERVICE
22/tcp open  ssh
```
The firewall on the server is disabled:

```
# systemctl status firewalld
○ firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; preset: enabled)
     Active: inactive (dead) since Sat 2024-10-19 17:56:30 EEST; 5min ago
   Duration: 1h 32min 30.299s
       Docs: man:firewalld(1)
    Process: 642 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/S>
   Main PID: 642 (code=exited, status=0/SUCCESS)
        CPU: 455ms
```

**Comment by kth8** [comment]
I have no idea what your network setup is which is why I included "If you are accessing from another computer then use the IP address of the server this is running on."

**Comment by Doroshenko-T** [comment]
I try  access both locally - http://localhost:8080 , and remotely - http:/192.168.1.100:8080
In any case, your llama-server is not responding.

**Comment by kth8** [comment]
See if it's running with `podman ps -a` on your server as well as `curl` command from the README. If those work but still not response from your desktop then there is probably is misconfiguration such as `http:/` instead of `http://`

**Comment by Doroshenko-T** [comment]
```
$ curl -N -H "Content-Type: application/json" -d '{"messages":[{"role":"user","content":"Why is the sky blue?"}]}' http://127.0.0.1:8080/v1/chat/completions
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```

```
$ podman ps -a
ERRO[0000] Refreshing container 042a0ec153bb19ac5684e4b195a4bcbaa4e7ce757eb3f5ecafa6c88b11046277: acquiring lock 0 for container 042a0ec153bb19ac5684e4b195a4bcbaa4e7ce757eb3f5ecafa6c88b11046277: file exists 
CONTAINER ID  IMAGE                                            COMMAND     CREATED      STATUS                    PORTS                   NAMES
042a0ec153bb  ghcr.io/kth8/llama-server:llama-3.2-1b-instruct              2 hours ago  Exited (132) 2 hours ago  0.0.0.0:8080->8080/tcp  llama1b
```

**Comment by kth8** [comment]
if you stopped it 2 hours ago then there's the problem. Use `podman start llama1b` to restart it.

**Comment by Doroshenko-T** [comment]
I didn't stop him. I don't even know how to stop him yet.
Okay, I did it.:

```
$ podman start llama1b
llama1b
```
And again I got the same result:

```
$ curl -N -H "Content-Type: application/json" -d '{"messages":[{"role":"user","content":"Why is the sky blue?"}]}' http://127.0.0.1:8080/v1/chat/completions
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```

**Comment by kth8** [comment]
No idea why that's the case. I think you are better off using [llamafile](https://github.com/Mozilla-Ocho/llamafile) instead which have complete instructions from A to Z. Here is the download link for 3.2 1B: 
https://huggingface.co/Mozilla/Llama-3.2-1B-Instruct-llamafile/blob/main/Llama-3.2-1B-Instruct.Q6_K.llamafile
Better to ask for help in discord for real time feedback and be able to talk over voice and share your screen:
https://discord.com/invite/yTPd7GVG3H

**Comment by Doroshenko-T** [comment]
I deleted podman. Then I installed and ran the true docker:

```
$ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c1ec31eb5944: Pull complete 
Digest: sha256:d211f485f2dd1dee407a80973c8f129f00d54604d2c90732e8e320e5038a0348
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.
```
So, everything is fine here.
Then executed:
```
$ sudo docker run \
    -d \
    --name llama1b \
    --init \
    -p 8080:8080/tcp \
    ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
Unable to find image 'ghcr.io/kth8/llama-server:llama-3.2-1b-instruct' locally
llama-3.2-1b-instruct: Pulling from kth8/llama-server
d31415fe5fdc: Pull complete 
0aacda3dfb23: Pull complete 
Digest: sha256:18202a21daef72feedf7f4e9ef16e9774412e01dc25563e66c803e3d63f191d7
Status: Downloaded newer image for ghcr.io/kth8/llama-server:llama-3.2-1b-instruct
131acee1e016424cfa68629741142409e338c9971617d827fd3d4752f562445c
```
But alas, the result is still sad:
```
$ sudo docker ps -a
CONTAINER ID   IMAGE                                             COMMAND           CREATED          STATUS                        PORTS     NAMES
131acee1e016   ghcr.io/kth8/llama-server:llama-3.2-1b-instruct   "/llama-server"   32 seconds ago   Exited (132) 25 seconds ago             llama1b
27790ab2881e   hello-world                                       "/hello"          3 minutes ago    Exited (0) 3 minutes ago                boring_engelbart
```

**Comment by kth8** [comment]
I don't know why the server is stopping itself when there is no reason it should or why port 8080 is not mapped to the host.

**Comment by kth8** [comment]
What computer are you running this on? Are you running out of RAM when trying to load the model?

**Comment by kth8** [comment]
Or you running this on a Raspberry Pi or something?

**Comment by Doroshenko-T** [comment]
CPU:	XEON E3 1245 v2
MBoard:	S1200KP
RAM:	16 GB
OS:		Alma 9.4

To the question "Why is the sky blue?" Llama 3.1 here gives a rate of 3.7...4.2 tokens/sec.

**Comment by kth8** [comment]
https://github.com/user-attachments/assets/d0cb0f69-2874-4f39-ad4f-af75008aa092

**Comment by Doroshenko-T** [comment]
Unfortunately, this video is not displayed in my browser for some reason.
Can I download it? Or present it as an AVI?

**Comment by kth8** [comment]
https://imgur.com/a/yLBoJBX

**Comment by Doroshenko-T** [comment]
Yes, now everything is good visible, you have llama-server working perfectly.
Let me ask you a few questions:
1. What OS do you use?
2. What CPU do you have?
3. What speed do you get for models in tokens/sec?
4. Why is your llama-server project better than llamafile?
5. Can you give another invite for Discord? Unfortunately, yTPd7GVG3H is no longer relevant

**Comment by kth8** [comment]
@T-Shilov I found a clue why `llama-server` is crashing. It runs fine on my modern desktop but when I try to run it on old and mobile CPUs that does not have AVX2 support it crashes. Your XEON E3 1245 v2 CPU is 10+ years old which does not have AVX2 support so `llama-server` is crashing. To run without AVX2 support `llama-server` need to be recompiled with `-DLLAMA_AVX2=off`.

**Comment by kth8** [comment]
I did some testing and without AVX support performance took a huge hit. I went from 20 token/s to 3 tokens/s.

**Comment by Doroshenko-T** [comment]
**kth8**, thank you very much for your guess! 🍺
I'm wondering on which processor did you achieve such a huge speed - 20 tokens per second? And how did you measure it?

Because I tested models the Llama-3.2-1B-Instruct.BF 16.llamafile and Meta-Llama-3-8B-Instruct.Q5_K_M.llamafile recommended by you.
I do not know how to objectively measure the speed of their work, but visually it seemed to me very very small.

**Comment by kth8** [comment]
After sending a request such as with the `curl` command the server prints out the token/s using `docker logs llama1b`
```
main: server is listening on 0.0.0.0:8080 - starting the main loop
srv  update_slots: all slots are idle
slot launch_slot_: id  0 | task 0 | processing task
slot update_slots: id  0 | task 0 | tokenizing prompt, len = 1
slot update_slots: id  0 | task 0 | prompt tokenized, n_ctx_slot = 682, n_keep = 0, n_prompt_tokens = 16
slot update_slots: id  0 | task 0 | kv cache rm [0, end)
slot update_slots: id  0 | task 0 | prompt processing progress, n_past = 16, n_tokens = 16, progress = 1.000000
slot update_slots: id  0 | task 0 | prompt done, n_past = 16, n_tokens = 16
slot      release: id  0 | task 0 | stop processing: n_past = 298, truncated = 0
slot print_timing: id  0 | task 0 | 
prompt eval time =     322.69 ms /    16 tokens (   20.17 ms per token,    49.58 tokens per second)
       eval time =   13643.32 ms /   283 tokens (   48.21 ms per token,    20.74 tokens per second)
      total time =   13966.01 ms /   299 tokens
srv  update_slots: all slots are idle
request: POST /v1/chat/completions 10.0.2.100 200
```
This the Llama3.2 1B on an Intel Kaby Lake i7 CPU. If you run the llamafile in server mode with `--server` it will also print it out to the console.

**Comment by Doroshenko-T** [comment]
**kth8**, thanks, I'll try to compile, although I don't know how to do it yet

**Comment by Doroshenko-T** [comment]
The AMD RX580 videocard provides a speed of ~25 tokens / sec.
Your Intel Kaby Lake i7 gives you a speed of 20 tokens / sec.
These are comparable speeds, right?

It turns out that me don't need to solve the complex problem of using the RX580 & ROCm, but need just buy a new powerful processor with AVX2 ?

**Comment by kth8** [comment]
Bigger models are slower to run than smaller models. CPU is only good enough to run small models at a usable speed which is why I only included small models here. You should not buy CPUs for the purpose of running LLMs since you will be limited by your system memory bandwidth. GPU will large amount of VRAM will be better for running LLM.

**Comment by Doroshenko-T** [comment]
Ok, thank you.  kth8, can you give another invite for Discord? Unfortunately, yTPd7GVG3H is no longer relevant

**Comment by kth8** [comment]
Here is to the Ollama discord: https://discord.com/invite/ollama

**Comment by Doroshenko-T** [comment]
I know that, but Discord  won't let me in, because me need an up-to-date invitation

**Comment by kth8** [comment]
I just saw that link on their Hugging Face page https://huggingface.co/Mozilla

**Comment by Doroshenko-T** [comment]
I saw it too. And what does that mean? Unfortunately I do not understand :-(
